# Site settings
title: Chenxi Liu
email: cxliu@google.com
description: > # this means to ignore newlines until "baseurl:"
  Proud AI Researcher
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://chenxi116.github.io" # the base hostname & protocol for your site
twitter_username: chenxi116
github_username:  chenxi116

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
